DROP TABLE IF EXISTS SETTINGS;

CREATE TABLE SETTINGS (
  id    BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  setting_name VARCHAR(255)                      NOT NULL,
  setting_value VARCHAR(255)  NOT NULL
);